//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfGisApp.GisService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GisService.IGisService")]
    public interface IGisService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGisService/GetAllCity", ReplyAction="http://tempuri.org/IGisService/GetAllCityResponse")]
        string GetAllCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGisService/GetAllCity", ReplyAction="http://tempuri.org/IGisService/GetAllCityResponse")]
        System.Threading.Tasks.Task<string> GetAllCityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGisService/GetWeatherCity", ReplyAction="http://tempuri.org/IGisService/GetWeatherCityResponse")]
        string GetWeatherCity(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGisService/GetWeatherCity", ReplyAction="http://tempuri.org/IGisService/GetWeatherCityResponse")]
        System.Threading.Tasks.Task<string> GetWeatherCityAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGisServiceChannel : WpfGisApp.GisService.IGisService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GisServiceClient : System.ServiceModel.ClientBase<WpfGisApp.GisService.IGisService>, WpfGisApp.GisService.IGisService {
        
        public GisServiceClient() {
        }
        
        public GisServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GisServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GisServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllCity() {
            return base.Channel.GetAllCity();
        }
        
        public System.Threading.Tasks.Task<string> GetAllCityAsync() {
            return base.Channel.GetAllCityAsync();
        }
        
        public string GetWeatherCity(int id) {
            return base.Channel.GetWeatherCity(id);
        }
        
        public System.Threading.Tasks.Task<string> GetWeatherCityAsync(int id) {
            return base.Channel.GetWeatherCityAsync(id);
        }
    }
}
